### ISSUE TITLE
Using the stick controls in a diagonal position

### ISSUE THREAD

**Issue by rycodge** [ecraven/g13#4]
Hello. The primary reason I use the g13 is because I can map the arrow keys from the keyboard to the control stick on the g13.

Just tried out this driver, however I noticed it doesn't scroll diagonally in games. Scrolling in one direction and rotating the stick to another causes input to stop. On the keyboard I can press two arrow keys at once and on the g13 I cannot. I was using dota2 for testing. This works just fine on Windows 7 (obviously).

Thanks for the work on this driver. Let me know how I can help.

**Comment by james-fowler** [comment]
The latest version has some enhancements to the stick configuration which might cover what you're looking for.  Take a look at the **stickzone** command - zones are allowed to overlap.
